name: Hello World

# Controls when the workflow will run
on:
  push:
    branches:
      - main # Run the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main # Run the workflow on pull request to the 'main' branch

# A workflow run is made up of one or more jobs
jobs:
  hello_world:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
