name: Demo Build and Deploy Workflow
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Demo Project
        run: >
          mkdir -p build

          echo "<!DOCTYPE
          html><html><head><title>Demo</title></head><body><h1>Hello,
          Abhishek!</h1><p>This is a demo build.</p></body></html>" >
          build/index.html
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Deploy to Demo Directory
        run: |
          mkdir -p ~/demo-deployment
          cp -R build/* ~/demo-deployment/
          echo "Demo deployment completed. Files are in ~/demo-deployment/"

